name:                h
version:             0.1.0.0
github:              "mengwong/h"
license:             BSD3
author:              "Wong Meng Weng"
maintainer:          "mwwong@smu.edu.sg"
copyright:           "2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mengwong/h#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- containers
- text
- boxes
- fgl

library:
  source-dirs: src

executables:
  h-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h

tests:
  h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h
